### ISSUE TITLE
Failing on running cAdvisor

### ISSUE THREAD

**Issue by borysl** [DanWahlin/Angular-Docker-Microservices#2]
CONDITIONS:
Windows 10
ACTION
clone and follow the instructions
EXPECTED
after docker-compose up everything is up and running
ACTUAL
$ docker-compose up
postgres is up-to-date
mongodb is up-to-date
Recreating nginx ...
Recreating aspnetcoreapp ...
Recreating nodeapp       ...
Recreating nginx         ... done
Recreating aspnetcoreapp ... done
Recreating nodeapp       ... done
ocker:/var/lib/docker"\nis not a valid Windows path'

ERROR: for cadvisor  Cannot create container for service cadvisor: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\docker:/var/lib/docker"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.

**Comment by DanWahlin** [comment]
I've never tried running that particular project on Windows (only Mac/Linux) so it looks like you've hit an issue with cAdvisor and the volumes that are defined in the compose file when run on Windows. In doing some research I can't find any examples of using Docker CE for Windows with cAdvisor/docker compose (note that cAdvisor is still running in a Linux container - the volumes that point back to the Windows machine seem to be the problem).

For now I'd recommend removing the cAdvisor service from the Docker Compose file to get the project going. Since I haven't found any examples of using cAdvisor with Docker CE for Windows I'm going to close the issue, but I'll update the readme. If I do come across a way to get it going on Windows I'll update the project.
